version: "3.7"
services:
  postgres:
    image: postgres:11
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-continuous_learning_app}
    volumes:
      - sara-sabr:/data/postgres
    ports:
      - "5432:5432"
volumes:
  sara-sabr:
    driver: local
